### ISSUE TITLE
What is K.txt?

### ISSUE THREAD

**Issue by zharvey-welltok** [openMVG/ImageDataset_SceauxCastle#3]
This morning I had my first successful "end-to-end" run with my reconstruction pipeline:
- I took the images from this repo (of Chateau de Sceaux) and used `tutorial_demp.py` to do initial SFM on them; then
- I used `openMVG_main_openMVG2MVE2` to prepare them for an MVE pipeline; then
- I used MVE to do the 3D reconstruction on them and produce a model; then
- I used mvs-texturing to generate a material/texture file for the model; then
- I imported the castle model into Blender (mesh + material) - **and it looks awesome!**

First baby step out of the way. Now I have a new series of images that I want to run through this pipeline (raw images -> OpenMVG -> MVE -> mvs-texturing -> Blender). So I am trying to understand `tutorial_demo.py` as well as this repo (so that I can venture out on my own and start using my own images, etc.).

One thing that seems very important, but I can't find documentation on, is the `images/K.txt` file in this repo:

```
2905.88 0 1416 
0 2905.88 1064
0 0 1
```
- What is this file, and what are its contents?
- Is the file format documented somewhere? How could I create my own using my own images?
- Is it even used? I don't see any mention of it in `tutorial_demo.py`, but I guess it could very well be used by one of the binaries called from that script...

Thanks in advance for any-and-all help!

**Comment by zharvey-welltok** [comment]
When running `openMVG_main_SfMInit_ImageListing` without any options, I did find a `-k` option that seems like it might be related to this `K.txt` file somehow:

```
[-k|--intrinsics] Kmatrix: "f;0;ppx;0;f;ppy;0;0;1"
```

Any connection there?

**Comment by pmoulon** [comment]
This option allow to configure manually the calibration matrix
See here to better undertand the classic pinhole camera model
http://openmvg.readthedocs.io/en/latest/openMVG/cameras/cameras/

In the tutorial demo this K file is not used, since the calibration matrix is build from some exif image data parsing and analysis of the sensor database file.
